import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter"
});
export const metadata = {
  title: "Alif Bima Mahendra",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased  ${inter.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
